### ISSUE TITLE
Should not panic when no host endpoint has been configured

### ISSUE THREAD

**Issue by askfongjojo** [oxidecomputer/oxide.rs#118]
This seems to be a recent regression. I accidentally left the OXIDE_* env vars un-configured and noticed that the cli panics on missing host endpoint:
```
root@oxz_nexus:~# oxide silo create --name ci --description "CI/CD" --discoverable true --identity-mode saml_jit
thread 'main' panicked at 'no authenticated hosts', cli/src/context.rs:24:30
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

root@oxz_nexus:~# RUST_BACKTRACE=1 oxide silo create --name ci --description "CI/CD" --discoverable true --identity-mode saml_jit
thread 'main' panicked at 'no authenticated hosts', cli/src/context.rs:24:30
stack backtrace:
   0: rust_begin_unwind
             at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/panicking.rs:64:14
   2: core::panicking::panic_display
             at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/panicking.rs:147:5
   3: core::panicking::panic_str
             at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/panicking.rs:131:5
   4: core::option::expect_failed
             at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/option.rs:1924:5
   5: core::option::Option<T>::expect
             at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/option.rs:786:21
   6: oxide::context::Context::client
             at /home/angela/oxide-sdk-and-cli/cli/src/context.rs:24:9
   7: oxide::main::{{closure}}
             at /home/angela/oxide-sdk-and-cli/cli/src/main.rs:169:46
   8: tokio::runtime::park::CachedParkThread::block_on::{{closure}}
             at /home/angela/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.27.0/src/runtime/park.rs:283:63
   9: tokio::runtime::coop::with_budget
             at /home/angela/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.27.0/src/runtime/coop.rs:107:5
  10: tokio::runtime::coop::budget
             at /home/angela/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.27.0/src/runtime/coop.rs:73:5
  11: tokio::runtime::park::CachedParkThread::block_on
             at /home/angela/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.27.0/src/runtime/park.rs:283:31
  12: tokio::runtime::context::BlockingRegionGuard::block_on
             at /home/angela/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.27.0/src/runtime/context.rs:315:13
  13: tokio::runtime::scheduler::multi_thread::MultiThread::block_on
             at /home/angela/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.27.0/src/runtime/scheduler/multi_thread/mod.rs:66:9
  14: tokio::runtime::runtime::Runtime::block_on
             at /home/angela/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.27.0/src/runtime/runtime.rs:304:45
  15: oxide::main
             at /home/angela/oxide-sdk-and-cli/cli/src/main.rs:177:5
  16: core::ops::function::FnOnce::call_once
             at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

root@oxz_nexus:~# env | grep OX
root@oxz_nexus:~# export OXIDE_HOST=http://192.168.1.21:80
root@oxz_nexus:~# export OXIDE_TOKEN=oxide-spoof-001de000-05e4-4000-8000-000000004007
root@oxz_nexus:~# oxide silo create --name ci --description "CI/CD" --discoverable true --identity-mode saml_jit
success
```
The version is at commit e3d3bacf5bbd5b443640f2cd8660f0923890d48c.

**Comment by askfongjojo** [comment]
No longer reproducible in the latest version.
