### ISSUE TITLE
CLI can't be built if .git is missing (e.g. downloaded zip)

### ISSUE THREAD

**Issue by iliana** [oxidecomputer/oxide.rs#188]
https://github.com/oxidecomputer/oxide.rs/blob/4d5d22804a092868f1ac5f73c5259db517b9b89e/cli/build.rs#L9-L13

This will eventually be a pain for downstream distribution packagers.

**Comment by iliana** [comment]
Also, if you patch out the check, you get a panic at runtime:

```
$ result/bin/oxide version
Oxide CLI 0.1.0
thread 'tokio-runtime-worker' panicked at 'called `Option::unwrap()` on a `None` value', cli/src/cmd_version.rs:31:41
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: JoinError::Panic(Id(17), ...)', cli/src/main.rs:56:10
```

**Comment by ahl** [comment]
> This will eventually be a pain for downstream distribution packagers.

I expected that we would steer people towards built artifacts e.g. from #19.

**Comment by iliana** [comment]
I think we can steer customers to pre-built artifacts but a certain type of customer will [tend to reach for distro tools](https://github.com/iliana/nixos-configs/blob/main/packages/oxide.nix) for [one reason or another](https://docs.brew.sh/How-to-Create-and-Maintain-a-Tap). Eventually one of these types of folks will upstream their work into a distro. If it's easy enough to make the equivalent of `cargo install` work without patches, even if we're less likely to support it, I think we should do that.
