### ISSUE TITLE
`project list` should not panic if the client is not authenticated

### ISSUE THREAD

**Issue by leftwo** [oxidecomputer/oxide.rs#391]
The CLI should not panic if it can't find an authenticated host:

Using this rev on my bench gimlet
```
EVT22200005 # ./oxide version
Oxide CLI 0.1.0-beta.5
Built from commit: 4959a447a543fb22511304a5f5f43df23b7ca9ee 
Oxide API: 0.0.1
```

I get this panic:
```
EVT22200005 # ./oxide project list
thread 'tokio-runtime-worker' panicked at 'no authenticated hosts', cli/src/context.rs:28:30
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: JoinError::Panic(Id(129), ...)', cli/src/main.rs:60:10
```

**Comment by ahl** [comment]
Now we get:

```console
$ oxide project list
no authenticated hosts; use oxide auth login to authenticate
```
